##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Oppacity config
windowrule = opacity 0.8 0.6 1,match:class .*
windowrule = opacity 1 0.8 1,match:class ^org.kde.pix$ 
windowrule = opacity 1 0.8 1,match:class ^com.github.rafostar.Clapper$ 
windowrule = opacity 1 0.8 1,match:class ^firefox$ 
windowrule = opacity 1 0.8 1,match:class ^MuseScore4$ 
windowrule = opacity 1 1 1,match:class ^firefox$, match:title ^Picture-in-Picture$
windowrule = opacity 1 0.6 1,match:class ^steam$
windowrule = opacity 1 0.8 1,match:class ^steam$, match:title ^$

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = proton-pass

    match:class = ^(Proton Pass)$

    float = yes
    center = yes
}

windowrule {
    name = Spotify

    match:class = ^spotify$   

    workspace = special:music
    suppress_event = [fullscreen, maximize, fullscreenoutput]
    float = false
    fullscreen_state = 0
    pseudo = false
    tile = true
}

windowrule {
    name = Proton Pass

    match:class = ^Proton Pass$   

    workspace = special:pass
    suppress_event = [fullscreen, maximize, fullscreenoutput]
    float = false
    fullscreen_state = 0
    pseudo = false
    tile = true
}

windowrule {
    name = Obsidian

    match:class = ^obsidian$   

    workspace = special:notes
    suppress_event = [fullscreen, maximize, fullscreenoutput]
    float = false
    fullscreen_state = 0
    pseudo = false
    tile = true
}

windowrule {
    name = Steam Firend list

    match:class = ^steam$   
    match:title = ^Friends List$
    float = true
}

windowrule {
    name = Thunar rename

    match:class = ^Thunar$   
    match:title = ^Rename ".*"$
    float = true
}

windowrule {
    name = firefox Picture in picture

    match:class = ^firefox$
	match:title = ^Picture-in-Picture$
    
    float = true
}

windowrule {
    name = Satty (screanshot anotation)

    match:class = ^com.gabm.satty$   
    float = true
    center = true
    max_size = (monitor_w*0.8) (monitor_h*0.8)

}
